export const PAGES = [
  {
    route: '/',
    output: 'index.html',
    title: 'Vip Streaming | Streaming por Assinatura',
    description: 'Conheça o Vip Streaming, serviço de streaming por assinatura com planos flexíveis, configuração orientada e atendimento direto pelo WhatsApp.',
    h1: 'Streaming simples. Do seu jeito.',
    label: 'Início',
    schema: 'home',
    indexable: true,
  },
  {
    route: '/planos/',
    output: 'planos/index.html',
    title: 'Planos de Streaming por Assinatura | Vip Streaming',
    description: 'Compare os ciclos mensal, trimestral e anual do Vip Streaming, consulte as condições atuais e fale com o atendimento antes de contratar.',
    h1: 'Planos para o seu ritmo',
    label: 'Planos',
    schema: 'service',
    indexable: true,
  },
  {
    route: '/como-funciona/',
    output: 'como-funciona/index.html',
    title: 'Como Funciona o Serviço | Vip Streaming',
    description: 'Veja como contratar o Vip Streaming: escolha o plano, confirme as condições pelo WhatsApp, receba as orientações e configure seu dispositivo.',
    h1: 'Começar é simples',
    label: 'Como funciona',
    schema: 'howto',
    indexable: true,
  },
  {
    route: '/dispositivos/',
    output: 'dispositivos/index.html',
    title: 'Dispositivos Compatíveis | Vip Streaming',
    description: 'Saiba quais tipos de dispositivos podem ser compatíveis com o Vip Streaming e o que verificar na internet e no aparelho antes da contratação.',
    h1: 'Assista nos seus dispositivos',
    label: 'Dispositivos',
    schema: 'collection',
    indexable: true,
  },
  {
    route: '/guia-streaming/',
    output: 'guia-streaming/index.html',
    title: 'Como Escolher um Serviço de Streaming | Guia VIP',
    description: 'Aprenda a avaliar um serviço de streaming: compatibilidade, conexão, atendimento, condições do plano, privacidade e suporte antes de assinar.',
    h1: 'Guia para escolher um serviço de streaming',
    label: 'Guia de streaming',
    schema: 'article',
    indexable: true,
  },
  {
    route: '/faq/',
    output: 'faq/index.html',
    title: 'Dúvidas sobre Streaming | Vip Streaming',
    description: 'Encontre respostas sobre planos, dispositivos, conexão, período de avaliação, pagamento, cancelamento e atendimento do Vip Streaming.',
    h1: 'Perguntas frequentes',
    label: 'Dúvidas',
    schema: 'faq',
    indexable: true,
  },
  {
    route: '/contato/',
    output: 'contato/index.html',
    title: 'Contato e Atendimento | Vip Streaming',
    description: 'Fale com o Vip Streaming pelo WhatsApp para consultar planos, compatibilidade, condições de avaliação, formas de pagamento e suporte à configuração.',
    h1: 'Fale com a Vip Streaming',
    label: 'Contato',
    schema: 'contact',
    indexable: true,
  },
  {
    route: '/privacidade/',
    output: 'privacidade/index.html',
    title: 'Política de Privacidade | Vip Streaming',
    description: 'Entenda como o site Vip Streaming trata dados pessoais, links para WhatsApp, registros técnicos, cookies e solicitações relacionadas à privacidade.',
    h1: 'Política de privacidade',
    label: 'Privacidade',
    schema: 'webpage',
    indexable: true,
  },
  {
    route: '/termos/',
    output: 'termos/index.html',
    title: 'Termos de Uso do Site | Vip Streaming',
    description: 'Consulte as regras de uso do site Vip Streaming, condições gerais, responsabilidades, informações comerciais e limites do conteúdo publicado.',
    h1: 'Termos de uso',
    label: 'Termos de uso',
    schema: 'webpage',
    indexable: true,
  },
  {
    route: '/404.html',
    output: '404.html',
    title: 'Página Não Encontrada | Vip Streaming',
    description: 'A página que você tentou acessar não foi encontrada. Use a navegação para voltar ao Vip Streaming, consultar planos ou falar com o atendimento.',
    h1: 'Página não encontrada',
    label: 'Página não encontrada',
    schema: 'webpage',
    indexable: false,
  },
];
